kind: pipeline
type: docker
name: pyzmq

platform:
  arch: arm

trigger:
  ref:
    - refs/tags/pyzmq-*

concurrency:
  limit: 1

clone:
  disable: true

steps:
- name: build-and-publish-pyzmq
  image: 192.168.1.125:5000/raspberrypios/buster:20211202
  environment:
    ID_ED25519:
      from_secret: id_ed25519
    ID_ED25519_PUB:
      from_secret: id_ed25519_pub
  commands:
  - # VERSION
  - echo $DRONE_TAG | sed 's|pyzmq-\(.*\).*|\1|' > version.txt
  - export VERSION=`cat version.txt`
  - # PREPARE SSH
  - mkdir -p ~/.ssh
  - echo "$ID_ED25519" > ~/.ssh/id_ed25519
  - chmod 600 ~/.ssh/id_ed25519
  - echo "$ID_ED25519_PUB" > ~/.ssh/id_ed25519.pub
  - chmod 644 ~/.ssh/id_ed25519.pub
  - git config --global user.email "drone@localhost.com"
  - git config --global user.name "drone"
  - ssh-keyscan github.com >> githubKey
  - ssh-keygen -lf githubKey
  - cat githubKey >> ~/.ssh/known_hosts
  - rm githubKey
  - # PREPARE SYSTEM
  - apt-get -qq update -y
  - apt-get -qq upgrade -y
  - apt-get -qq install git cython3 python3-distutils -y
  - wget "https://bootstrap.pypa.io/get-pip.py"
  - python3 get-pip.py
  - python3 -m pip install wheel packaging
  - # PYZMQ BUILD
  - git clone https://github.com/zeromq/pyzmq.git
  - cd pyzmq
  - git fetch --all --tags
  - git checkout tags/$VERSION -b branch$VERSION
  - python3 -m pip install -e .
  - python3 setup.py bdist_wheel
  - ls -lh dist
  - cd ..
  - # CLEEP-LIBS-PREBUILD STUFF
  - git clone git@github.com:CleepDevice/cleep-libs-prebuild.git
  - mkdir -p cleep-libs-prebuild/pyzmq
  - cp -a pyzmq/dist/pyzmq-*.whl cleep-libs-prebuild/pyzmq/.
  - cd cleep-libs-prebuild
  - git add .
  - git commit -m "Add pyzmq "$VERSION
  - git push -u origin HEAD


---
kind: pipeline
type: docker
name: gevent

platform:
  arch: arm

trigger:
  ref:
    - refs/tags/gevent-*

concurrency:
  limit: 1

clone:
  disable: true

steps:
- name: build-and-publish-gevent
  image: 192.168.1.125:5000/raspberrypios/buster:20211202
  environment:
    ID_ED25519:
      from_secret: id_ed25519
    ID_ED25519_PUB:
      from_secret: id_ed25519_pub
  commands:
  - # VERSION
  - echo $DRONE_TAG | sed 's|gevent-\(.*\).*|\1|' > version.txt
  - export VERSION=`cat version.txt`
  - # PREPARE SSH
  - mkdir -p ~/.ssh
  - echo "$ID_ED25519" > ~/.ssh/id_ed25519
  - chmod 600 ~/.ssh/id_ed25519
  - echo "$ID_ED25519_PUB" > ~/.ssh/id_ed25519.pub
  - chmod 644 ~/.ssh/id_ed25519.pub
  - git config --global user.email "drone@localhost.com"
  - git config --global user.name "drone"
  - ssh-keyscan github.com >> githubKey
  - ssh-keygen -lf githubKey
  - cat githubKey >> ~/.ssh/known_hosts
  - rm githubKey
  - # PREPARE SYSTEM
  - apt-get -qq update -y
  - apt-get -qq upgrade -y
  - apt-get -qq install git python3-distutils -y
  - wget "https://bootstrap.pypa.io/get-pip.py"
  - python3 get-pip.py
  - # GEVENT BUILD
  - python3 -m pip install virtualenv
  - virtualenv gevent-env
  - cd gevent-env
  - git clone git@github.com:gevent/gevent.git
  - . bin/activate
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - . "$HOME/.cargo/env"
  - python3 -m pip install wheel packaging
  - cd gevent
  - git fetch --all --tags
  - git checkout tags/$VERSION -b branch$VERSION
  - python3 -m pip install -r dev-requirements.txt
  - python3 setup.py bdist_wheel
  - ls -lh dist
  - cd ..
  - deactivate
  - ls -lh gevent/dist/
  - cd ..
  - # CLEEP-LIBS-PREBUILD STUFF
  - git clone git@github.com:CleepDevice/cleep-libs-prebuild.git
  - mkdir -p cleep-libs-prebuild/gevent
  - cp -a gevent-env/gevent/dist/gevent-*.whl cleep-libs-prebuild/gevent/.
  - cd cleep-libs-prebuild
  - git add .
  - git commit -m "Add gevent "$VERSION
  - git push -u origin HEAD

